language: julia
sudo: false
os:
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - xvfb-run julia -e 'Pkg.clone(pwd());
          println(BinDeps.debug("Gtk"));
          Pkg.test("Gtk"; coverage=true)'
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then
          julia -e 'cd(Pkg.dir("Gtk"));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())';
      fi
